### ISSUE TITLE
Error if img.ini is not found.

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#15]
**Describe the bug**

**To Reproduce**
1. Get a VNDS novel without an img.ini file;
2. Launch it with VNDS-LOVE;
3. See error.

**Expected behavior**
The Visual Novel working correctly. It should either default to a resolution of 256x192 when an img.ini file isn't found (like the Android VNDS Interpreter does) or automatically detect the size of the images in the background folder.

**Screenshots**
![error](https://user-images.githubusercontent.com/29778535/93721845-b0364400-fb60-11ea-9a08-ef223922afa1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Opera GX (Not sure why that matters. Might want to consider removing this from the issue template.)
 - Version: Latest release (0.02)

**Additional context**
The 0.02 release appears to be quite outdated so there's a possibility that the issues has already been resolved. Looking at the commits though, that doesn't appear to be the case.

[log.txt](https://github.com/ajusa/VNDS-LOVE/files/5252576/log.txt)

**Comment by ajusa** [comment]
Good catch! I've fixed the issue template as well, that was the default.

I think I'll have it try to automatically set the resolution based on the first background image that it sees (unless there is an img.ini), do you think that would be acceptable? Not sure if all of the background images are guaranteed to be the same size, even though they should be.

I will *eventually* get around to fixing this along with the other issues, life's been pretty crazy for me recently. This project isn't abandoned or anything.

**Comment by poudink** [comment]
Yeah that should be fine. All background images are supposed to be the same size. If they aren't, then the VN's got a pretty big problem.

**Comment by ajusa** [comment]
Fixed with https://github.com/ajusa/VNDS-LOVE/commit/c537775981ad1d864ed713b9e238aafcd7f8a46d
You can also test it out by downloading the build artifact for your system under https://github.com/ajusa/VNDS-LOVE/actions, clicking on the last run, and scrolling down to the bottom to see the downloads.
