### ISSUE TITLE
text ! not implemented

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#18]
**Describe the bug**
The "text !" command isn't implemented. It's supposed to indicate that no text is to be displayed but that you need to wait for the confirmation key to continue to the next line in the script. The command is used in Adagio at the very start after the credit lines.

**To Reproduce**
1. Launch Adagio
2. Wait

**Expected behavior**
VNDS-LOVE should stop at the text ! lines instead of skipping over them.

**Desktop (please complete the following information):**
 - OS/Machine: Windows 10 64-bit
 - 0.05

Please attach a log file (located in the same directory as `novels`) if you can to help debug the issue. Thanks!
[log.txt](https://github.com/ajusa/VNDS-LOVE/files/5761186/log.txt)

**Comment by ajusa** [comment]
Should be fixed with https://github.com/ajusa/VNDS-LOVE/commit/c937d4e65b24dcf3564465f86d7089b4d2565db7, making a new release now
