### ISSUE TITLE
Text Backlog

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#23]
**Is your feature request related to a problem? Please describe.**
While not a feature of the original VNDS software per se, this feature would be required to compensate for a difference in presentation between VNDS-LOVE and the original VNDS software. The original VNDS didn't use ADV text boxes but instead used the entire bottom screen of the DS to display text, in a format much more similar to NVL visual novels. This means that previous text could easily be seen above the new text and you could simply back up with the stylus to see even older text. With the ADV format that VNDS-LOVE uses, this is obviously not possible.

**Describe the solution you'd like**
A backlog button that shows a list of all text that has been displayed since VNDS-LOVE was last launched. This is often mapped to the up arrow key in visual novels on PC.

**Describe alternatives you've considered**
An NVL option. It would also solve this problem, and would be closest to the way the original VNDS software displayed text, but may not be preferable all the time. It may be a good idea to have both an NVL option and a backlog.

**Comment by ajusa** [comment]
Had no idea this was a distinction. I think the best idea for now would be using the ADV text boxes along with an option to view the older text and scroll up through it. I would definitely be interested in having an NVL style overlay, but I think that the majority of people might not like it if the text covers the entire screen (this was the main reason I used ADV).
I have nothing against adding NVL in the future (should be theoretically possible) but for now I'll focus on ADV.

**Comment by ajusa** [comment]
Should work as of https://github.com/ajusa/VNDS-LOVE/commit/ecf97984b55bf3579f77c5621455d2c94858541e
Looks pretty ugly but I'll work on the aesthetic another time once there aren't any bugs reported with it.
