### ISSUE TITLE
"Repeat SFX" Button

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#24]
**Is your feature request related to a problem? Please describe.**
Missing feature from the original VNDS software.

**Describe the solution you'd like**
A button that repeats the last SFX that has been played. On the original VNDS, this is a touch screen button.

**Describe alternatives you've considered**
Most visual novels instead have a feature that allows replaying the SFX tied to each line of text from the backlog menu. While VNDS-LOVE doesn't have a backlog menu, adding one has been discussed in another issue (https://github.com/ajusa/VNDS-LOVE/issues/23). This would probably be better than the "replay SFX" button the original VNDS has, but would be harder to implement and has a currently unimplemented feature as a prerequisite.

**Comment by ajusa** [comment]
I think it would be possible to have the sound effect play with the scrolled text. There is no way of telling exactly which line it is tied to though, but I would assume that the sound plays before the text? Or it could play after (might vary between novels)? What I'm imagining is a scrollable box that has lines of text, and every once in a while a line that just has [Sound Effect] on it. That could then be selected to play the sound. That might be a little clunky, but it would get rid of that issue.
Example
```
[Sound Effect]
Here is some text that was displayed previously
[Sound Effect]
That sound has the voice for this text
Here is some more text with the voice coming out on the next
[Sound Effect]
```
Where selecting [Sound Effect] would play that sound.

**Comment by ajusa** [comment]
Should be working with https://github.com/ajusa/VNDS-LOVE/commit/d774843394963ea2fa730467dab1f403ac9f7d3a
I'll need to tweak the code a little so it is a bit nicer, but it should be functional.
