### ISSUE TITLE
Better Visual Novel Selection Menu

### ISSUE THREAD

**Issue by poudink** [ajusa/VNDS-LOVE#27]
**Is your feature request related to a problem? Please describe.**
Missing feature from the original VNDS software. Most VNDS novels had a 32x32 icon (stored as icon.png in the visual novel folder) and a 100x75 thumbnail (stored as thumbnail.png in the visual novel folder). The icon was displayed left of the visual novel's name in the visual novel selection menu and the thumbnail was displayed on the top screen when the visual novel was selected. Additionally, the Android visual novel interpreters added support for high resolution thumbnails and icons, which were placed in the same folder as the low resolution ones and were named icon-high.png/thumbnail-high.png. When present, they were used instead of their low resolution counterparts. These icons and thumbnails are currently completely unused, and the current selection screen is overall very bare.

**Describe the solution you'd like**
Complete revamp of the visual novel selection screen. See mock-up below.

**Additional context**
Because a picture is worth a thousand words, I made a very crude mock-up of what I had in mind.
![Mockup](https://user-images.githubusercontent.com/29778535/103842381-cf030c80-5063-11eb-8737-2040c5c61f9d.png)
Screenshot of the menu from the original VNDS.
![Original VNDS screenshot](https://user-images.githubusercontent.com/29778535/103842840-bc3d0780-5064-11eb-8904-45a9be5a049b.png)

**Comment by ajusa** [comment]
Should be done with https://github.com/ajusa/VNDS-LOVE/commit/23ba0f3a01f2d8af032146f5c421b517da689100!
![image](https://user-images.githubusercontent.com/7073362/104113546-bba4ab00-52c8-11eb-933b-75478576643a.png)
As a side note, it turns out that the thumbnail/icons can also be in jpg, so I had to account for that as well.
