### ISSUE TITLE
[SWITCH] Errors in games (Kikokugai The Cyber Slayer and others)

### ISSUE THREAD

**Issue by JrRadiant** [ajusa/VNDS-LOVE#31]
**Describe the bug**
The game just hangs with the latest build.

**To Reproduce**
1. Start the game
2. Press the A three times.

**Expected behavior**
Playing the game.

**Screenshots**
![err](https://user-images.githubusercontent.com/61790774/106350861-5578da00-6302-11eb-8f35-29f2624cf6ce.jpg)

**Desktop (please complete the following information):**
 - Machine: [Nintendo Switch]
 - Version of VNDS-LOVE [e.g. 0.0.9]

**Additional context**
Crash log is here:
[crash.txt](https://github.com/ajusa/VNDS-LOVE/files/5897564/crash.txt)
[log.txt](https://github.com/ajusa/VNDS-LOVE/files/5897565/log.txt)

**Comment by ajusa** [comment]
Thanks for filing this bug report! It seems that one of the audio files (cyborg_00_arm01.aac) is super messed up and non-standard encoded. Of course, VNDS-LOVE shouldn't try to crash if it can't read the file, it should skip over it. I'll try and have a fix out for this either today or tomorrow.

Slightly more technical details:
The output from trying to parse the file on the desktop version of LOVE2D (which has support for more audio) results in 
```
Note: Illegal Audio-MPEG-Header 0x24980911 at offset 2356.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[src/libmpg123/parse.c:1365] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
```
The actual format of the audio seems to be 
```
General
Complete name                            : cyborg_00_arm01.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 6.61 KiB
Overall bit rate mode                    : Variable

Audio
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 2
Codec ID                                 : 2
Bit rate mode                            : Variable
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 22.05 kHz
Frame rate                               : 21.533 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 6.61 KiB (100%)
```
I don't think actually playing the audio is fixable within VNDS-LOVE. Either Love2D needs to add support, or someone needs to re-encode those AAC files to fix the header issues.

**Comment by JrRadiant** [comment]
Thank you a lot for this great port and the fast response, of course!..

Ehm, right now I've in my list many games to test. Won't I bother you with some next bug reports if I'll encounter any?

**Comment by ajusa** [comment]
Hm, I'd prefer that you make bug reports after I push out a fix. That way you don't end up making 10 bug reports for different novels that were all caused by the same bug.
If the error you are getting for a different novel is different from this one though, feel free to make another bug report.

**Comment by JrRadiant** [comment]
Got it!

**Comment by drewbitt** [comment]
Kikokugai The Cyber Slayer works in 0.0.11 for Switch. I can start it now.

**Comment by ajusa** [comment]
Yep, it will work but none of the audio will play unless it is converted to something other than AAC, such as mp3 or ogg vorbis.
